-- Rust 专属快捷键 (buffer-local，仅影响 .rs 文件)
-- 与全局 <leader>u(测试/调试)/<leader>g(git)/<leader>s(snacks) 隔离，使用 <leader>r 组
local bufnr = vim.api.nvim_get_current_buf()
local map = function(lhs, rhs, desc)
  vim.keymap.set("n", lhs, rhs, { silent = true, buffer = bufnr, desc = desc })
end

map("<leader>rr", function()
  vim.cmd.RustLsp("runnables")
end, "[Rust] Runnables")
map("<leader>rd", function()
  vim.cmd.RustLsp("debuggables")
end, "[Rust] Debuggables")
map("<leader>re", function()
  vim.cmd.RustLsp("expandMacro")
end, "[Rust] Expand macro")
map("<leader>rc", function()
  vim.cmd.RustLsp("openCargo")
end, "[Rust] Open Cargo.toml")
map("<leader>ra", function()
  vim.cmd.RustLsp("codeAction")
end, "[Rust] Code action (grouped)")
map("<leader>rg", function()
  vim.cmd.RustLsp("crateGraph")
end, "[Rust] Crate graph")
map("<leader>rh", function()
  vim.cmd.RustLsp({ "hover", "actions" })
end, "[Rust] Hover actions")
-- 覆盖全局 gh: Rust 文件用 rustaceanvim 的 hover actions(带 Run/Debug 按钮)
-- 仅 buffer-local 生效，不影响 TS/其它文件的 gh
map("gh", function()
  vim.cmd.RustLsp({ "hover", "actions" })
end, "[Rust] Hover actions")
